# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ master ]

jobs:

  Testing:
    runs-on: macos-latest
    
    steps:
      - name: Hello World action
        uses: novpeter/hello-world-js-action@v1.0
        with:
         who-to-greet: 'Mona the Octocat'
