# This is a basic workflow to help you get started with Actions

name: Educational review CI

on:
  pull_request:
    branches: [ master ]

jobs:
          
  XcodeTesting:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
          
      - name: Install tree
        run: brew install tree
        shell: bash

      - name: Clone XCResultParser
        run: mkdir ${{ github.workspace }}/Scripts
          && mkdir ${{ github.workspace }}/Scripts/xcresult-parser
          && cd ${{ github.workspace }}/Scripts/xcresult-parser
          && git clone https://github.com/novpeter/xcresult-parser.git ${{ github.workspace }}/Scripts/xcresult-parser
        shell: bash 
        
      - name: Show hierarchy
        run: tree
        shell: bash
        
      - name: Parse .xcresult file
        run: cd ${{ github.workspace }}/Scripts/xcresult-parser
          && swift build
        shell: bash 
