# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ master ]

jobs:

  Testing:
    runs-on: macos-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        
      - name: Xcode Test
        uses: devbotsxyz/xcode-test@v1.1.0
        with:
          destination: 'platform=iOS Simulator,OS=14.4,name=iPhone 12'
