# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ master ]

jobs:

  Testing:
    runs-on: macos-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        
      - name: Xcode Test
        uses: novpeter/xcode-run-tests-action@v1.0.1
