# This is a basic workflow to help you get started with Actions

name: Educational review CI

on:
  pull_request:
    branches: [ master ]

jobs:

  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        
      - name: GitHub Action for SwiftLint
        uses: novpeter/action-swiftlint@1.1
        
      - name: Show folder hierarchy
        run: tree
        shell: bash

  XcodeTesting:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        
      - name: Xcode Test
        uses: novpeter/xcode-run-tests-action@v1.0.10
        with:
          result-bundle-path: 'AutomatisationProject/TestResults'
