# This is a basic workflow to help you get started with Actions

name: Educational review CI

on:
  pull_request:
    branches: [ master ]

jobs:

  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        
      - name: GitHub Action for SwiftLint
        uses: novpeter/action-swiftlint@1.1
        
      - name: Show folder hierarchy
        run: tree
        shell: bash
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: swift-lint-results
          path: ${{ github.workspace }}/SwiftLintResult.txt
          
  XcodeTesting:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        
      - name: Install tree
        run: brew install tree
        shell: bash
        
      - name: Xcode Test
        uses: novpeter/xcode-run-tests-action@v1.0.10
        with:
          result-bundle-path: ${{ github.workspace }}/Logs/TestResults
          
      - name: Show hierarchy 
        run: tree
        shell: bash
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: xcode-test-results
          path: ${{ github.workspace }}/Logs/TestResults.xcresult
