# This is a basic workflow to help you get started with Actions

name: Educational review CI

on:
  pull_request:
    branches: [ master ]

jobs:
          
  XcodeTesting:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        
      - name: Xcode Test
        uses: novpeter/xcode-run-tests-action@v1.0.35
        with:
          result-bundle-path: ${{ github.workspace }}/Logs/TestResults
          screen-record-bundle-path: ${{ github.workspace }}/Logs/ScreenRecording.mp4
          
      - name: Show hierarchy 
        run: brew install tree; tree
        shell: bash
        
      - run: mkdir ${{ github.workspace }}/Scripts
        shell: bash
        
      - run: mkdir cd ${{ github.workspace }}/Scripts
        shell: bash
        
      - name: Clone parser
        run: git clone https://github.com/novpeter/xcresult-parser.git
        shell: bash
        
      - run: cd ${{ github.workspace }}/Scripts/xcresult-parser
        shell: bash
       
      - run: swift build
        shell: bash 
      
      - name: Parse .xcresult file and save to /Logs
        run: swift run XCResultParser ${{ github.workspace }}/Logs/TestResults > ${{ github.workspace }}/Logs/TestResults.txt
        shell: bash 
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: xcode-test-results
          path: ${{ github.workspace }}/Logs/TestResults.txt
