# This is a basic workflow to help you get started with Actions

name: Educational review CI

on:
  pull_request:
    branches: [ master ]

jobs:

  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        
      - name: GitHub Action for SwiftLint
        uses: novpeter/action-swiftlint@1.1
        
      - name: Show workspace path
        run: echo ${{ github.workspace }}
        shell: bash
        
      - name: Show folder hierarchy
        run: tree
        shell: bash
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: swift-lint-results
          path: ${{ github.workspace }}/SwiftLintResults.txt
